/** shared loading placeholders; all generated by AI coming from daisy ui docs */

export function ProductPageSkeleton() {
  return (
    <div className="grid gap-10 md:grid-cols-2">
      <div className="w-full skeleton aspect-square rounded-box" />
      <div className="space-y-4">
        <div className="w-3/4 h-8 skeleton" />
        <div className="w-1/2 h-12 skeleton" />
        <div className="w-full h-40 skeleton" />
      </div>
    </div>
  );
}

export function CartSkeleton({ lines = 3 }) {
  const n = Math.min(Math.max(lines, 1), 8);
  return (
    <div className="grid gap-10 lg:grid-cols-[1fr_320px]">
      <ul className="space-y-4">
        {Array.from({ length: n }).map((_, i) => (
          <li
            key={i}
            className="border shadow-sm card card-side border-base-300 bg-base-100"
          >
            <div className="p-4">
              <div className="w-24 h-24 skeleton rounded-box" />
            </div>
            <div className="flex-row flex-wrap gap-4 justify-between items-center min-w-0 card-body">
              <div className="flex-1 space-y-3 min-w-0">
                <div className="w-48 max-w-full h-6 skeleton" />
                <div className="w-28 h-4 skeleton" />
                <div className="flex flex-wrap gap-3 items-center">
                  <div className="w-28 h-8 skeleton" />
                  <div className="w-16 h-6 skeleton" />
                </div>
              </div>
              <div className="w-20 h-6 skeleton" />
            </div>
          </li>
        ))}
      </ul>
      <aside className="p-6 border shadow-md card border-base-300 bg-base-100">
        <div className="flex gap-4 justify-between">
          <div className="w-20 h-4 skeleton" />
          <div className="w-24 h-4 skeleton" />
        </div>
        <div className="mt-6 w-full h-12 rounded-lg skeleton" />
        <div className="mt-4 w-full h-10 skeleton" />
      </aside>
    </div>
  );
}

export function OrdersListSkeleton() {
  return (
    <div className="space-y-4">
      {[1, 2, 3, 4].map((i) => (
        <div
          key={i}
          className="border shadow-sm card border-base-300 bg-base-100"
        >
          <div className="flex-row flex-wrap gap-4 items-center py-5 card-body sm:gap-5">
            <div className="rounded-2xl skeleton size-22 shrink-0" />
            <div className="flex-1 space-y-3 min-w-0">
              <div className="w-40 h-5 skeleton" />
              <div className="w-56 max-w-full h-4 skeleton" />
              <div className="flex flex-wrap gap-2 items-center">
                <div className="w-20 h-6 rounded-full skeleton" />
                <div className="w-24 h-4 skeleton" />
              </div>
            </div>
            <div className="w-24 h-8 skeleton shrink-0" />
          </div>
        </div>
      ))}
    </div>
  );
}

export function AdminProductsTableSkeleton() {
  return (
    <div className="overflow-x-auto border rounded-box border-base-300 bg-base-100">
      <table className="table">
        <thead>
          <tr>
            {[1, 2, 3, 4, 5, 6, 7].map((i) => (
              <th key={i} className={i === 1 ? "w-24" : undefined}>
                <div
                  className={`skeleton ${i === 1 ? "h-4 w-14" : "h-4 w-16"}`}
                />
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {[1, 2, 3, 4, 5, 6].map((row) => (
            <tr key={row}>
              <td>
                <div className="mx-auto w-14 h-14 rounded-xl skeleton shrink-0 sm:h-18 sm:w-18" />
              </td>
              {[2, 3, 4, 5, 6, 7].map((col) => (
                <td key={col}>
                  <div className="w-full h-5 skeleton max-w-32" />
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function OrderDetailSkeleton() {
  return (
    <div className="space-y-8 text-left">
      <div className="w-40 h-9 skeleton" />
      <div className="overflow-hidden rounded-2xl border shadow-lg border-base-300 bg-base-100">
        <div className="px-5 py-6 bg-base-200/50 sm:px-8 sm:py-8">
          <div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between">
            <div className="space-y-3">
              <div className="w-28 h-4 skeleton" />
              <div className="w-48 max-w-full h-9 skeleton" />
              <div className="w-64 max-w-full h-4 skeleton" />
              <div className="w-full max-w-md h-3 skeleton" />
            </div>
            <div className="pt-4 space-y-3 border-t border-base-300/80 lg:border-t-0 lg:pt-0 lg:text-right">
              <div className="w-20 h-8 rounded-full skeleton lg:ml-auto" />
              <div className="w-32 h-10 skeleton lg:ml-auto" />
            </div>
          </div>
        </div>
        <div className="px-5 py-4 border-t border-base-300 sm:px-8">
          <div className="w-full max-w-2xl h-4 skeleton" />
          <div className="mt-2 w-full max-w-xl h-4 skeleton" />
        </div>
      </div>
      <div className="w-full max-w-md h-10 rounded-lg skeleton" />
      <div className="w-full h-64 rounded-2xl skeleton" />
    </div>
  );
}

export function OrderVideoSkeleton() {
  return (
    <div className="space-y-4">
      <div className="w-40 h-10 skeleton" />
      <div className="skeleton min-h-[50vh] w-full rounded-box" />
    </div>
  );
}

export function OrderChatPanelSkeleton() {
  return (
    <div className="space-y-4">
      <div className="border shadow-sm card border-base-300 bg-base-100">
        <div className="flex-row flex-wrap gap-4 items-start card-body">
          <div className="w-12 h-12 skeleton shrink-0 rounded-box" />
          <div className="flex-1 space-y-2 min-w-0">
            <div className="w-48 h-6 skeleton" />
            <div className="w-full max-w-lg h-4 skeleton" />
            <div className="w-2/3 max-w-md h-4 skeleton" />
          </div>
        </div>
      </div>
      <div className="flex h-[560px] flex-col overflow-hidden rounded-box border border-base-300 bg-base-100">
        <div className="p-4 border-b border-base-300">
          <div className="w-56 h-8 skeleton" />
        </div>
        <div className="flex flex-col flex-1 gap-3 p-4">
          <div className="w-3/4 max-w-md h-16 rounded-lg skeleton" />
          <div className="ml-auto w-2/3 max-w-sm h-14 rounded-lg skeleton" />
          <div className="w-4/5 max-w-lg h-20 rounded-lg skeleton" />
        </div>
        <div className="p-3 border-t border-base-300">
          <div className="w-full h-10 rounded-lg skeleton" />
        </div>
      </div>
    </div>
  );
}
